version: '3'
services:

  nginx-container:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-container
    restart: always
    ports:
      - "443:443"

  mariadb-container:
    build: ./mariadb
    image: mariadb-container
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_db
    volumes:
      - ./mariadb/volume:/var/lib/mysql #REMPLACER PAR /home/jabenjam/data/volumemariadb
    ports:
      - "3306:3306"
      
  wordpress-container:
    build: ./wordpress
    image: wordpress-container
    depends_on:
      - mariadb-container
    links:
      - mariadb-container
    restart: always
    environment:
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        WORDPRESS_DB_HOST: mariadb_container:3306
        WORDPRESS_DB_NAME: wp_db
      volumes:
        - ./wordpress/volume:/usr/share/wordpress #REMPLACER PAR /home/jabenjam/data/volumemariadb
        ports:
          - "9000:9000"