version: '3'

services:
  mariadb-container:
    build: ./mariadb
    image: mariadb-container
    restart: always
    env_file:
      - "./.env"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx-container:
      build: ./nginx
      image: nginx-container
      depends_on:
        - wordpress-container
      restart: unless-stopped
      volumes:
        - wordpress:/var/www/wordpress
      ports:
        - "443:443"
      
  wordpress-container:
    build: ./wordpress
    image: wordpress-container
    depends_on:
      - mariadb-container
    restart: unless-stopped
    env_file:
      - "./.env"
    volumes:
     - wordpress:/var/www/wordpress
    ports:
      - "9000:9000"


volumes:
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/jabenjam/data/wordpress
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/jabenjam/data/mysql

# IMAGES OFFICIELLES

#  wordpress-container:
#    image: wordpress:5.7.2-php7.3-fpm
#    depends_on:
#      - mariadb-container
#    restart: unless-stopped
#    env_file:
#      - "./.env"
#    ports:
#      - "9000:9000"
#
#  mariadb-container:
#    image: mariadb
#    restart: always
#    env_file:
#      - "./.env"
#    #volumes:
#    #  - /home/jabenjam/data/db-logs:/var/log/mysql #debug volume
#    #  - /home/jabenjam/data/db:/var/lib/mysql
#    ports:
#      - "3306:3306"

networks:
  default:
    external:
      name: inception_network