version: '3'

services:
# IMAGES PERSO
  mariadb-container:
    build: ./mariadb
    image: mariadb-container
    restart: always
    env_file:
      - "./.env"
    #volumes:
    #  - /home/jabenjam/data/db-logs:/var/log/mysql #debug volume
    #  - /home/jabenjam/data/db:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress-container:
    build: ./wordpress
    image: wordpress-container
    depends_on:
      - mariadb-container
    restart: unless-stopped
    env_file:
      - "./.env"
    #volumes:
    # - /home/jabenjam/data/wp:/var/www/html
    ports:
      - "9000:9000"

  nginx-container:
    build: ./nginx
    image: nginx-container
    depends_on:
      - wordpress-container
    restart: unless-stopped
    ports:
      - "443:443"


# IMAGES OFFICIELLES

#  wordpress-container:
#    image: wordpress:5.7.2-php7.3-fpm
#    depends_on:
#      - mariadb-container
#    restart: unless-stopped
#    env_file:
#      - "./.env"
#    ports:
#      - "9000:9000"
#
#  mariadb-container:
#    image: mariadb
#    restart: always
#    env_file:
#      - "./.env"
#    #volumes:
#    #  - /home/jabenjam/data/db-logs:/var/log/mysql #debug volume
#    #  - /home/jabenjam/data/db:/var/lib/mysql
#    ports:
#      - "3306:3306"

networks:
  default:
    external:
      name: inception_network